# -*- coding: utf-8 -*-
"""fibonacci

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqiCJebXgEJ2n20ZH_39mTMyThkrul_4
"""

n = int(input("Enter the number of terms: "))
a, b = 0, 1

for i in range(n):
    print(a, end=" ")
    a, b = b, a + b